### ISSUE TITLE
[1.7.12] iPad Mini / iOS 8.3 - Albums - All photo folder is empty after pull down to refresh

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#244]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Open All Photos folder on Albums screen
4. Pull down to refresh all items

Expected result: User sees all photos in the current folder

Actual result: User sees empty All Photos folder

Video: [photo.zip](https://github.com/Lomotif/lomotif-ios-issues/files/189727/photo.zip)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa @vysohanych I can replicate it every time with iPhone 6 / iOS 9.3.

This bug is applicable to All videos and All photos - both the categories.

![img_1072](https://cloud.githubusercontent.com/assets/9691390/14058035/754b37c2-f338-11e5-86db-a58155aaba9e.PNG)

![img_1073](https://cloud.githubusercontent.com/assets/9691390/14058036/755444ac-f338-11e5-9070-d906ce0b1d5e.PNG)

![img_1074](https://cloud.githubusercontent.com/assets/9691390/14058034/754aea38-f338-11e5-8e53-7c882c5539a4.PNG)

![img_1075](https://cloud.githubusercontent.com/assets/9691390/14058037/755515a8-f338-11e5-9bf9-d8a2d82c9988.PNG)

![img_1076](https://cloud.githubusercontent.com/assets/9691390/14058033/74ee7a82-f338-11e5-9681-89edc0b45d86.PNG)

**Comment by Dipamit** [comment]
This issue already posted #238. Seem duplicate in new version.

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@e1ecb9eeb15c4ce96dbe76a353eb1299212bf247
